### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rajnishpatel17100**
Added some more information to Readme file

### CODE REVIEW

**Review by rajnish17100042 — CHANGES_REQUESTED** [review]
This is a correct explanation but you need to add more information to it then only I will approve your pull request (PR)

**Comment by rajnish17100042** [comment]
This need to add more information

**Comment by rajnishpatel17100** [comment]
This is correct please approve it

**Comment by rajnish17100042** [comment]
Ok fine I have merged your changes

**Pull request merged**
